# Generated by Django 5.1.6 on 2025-06-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arduino', '0001_initial'),
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Está excluido?')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('business_name', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=14, verbose_name='Numero de telefone')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('address', models.ManyToManyField(related_name='entrepises', to='core.address', verbose_name='Endereços')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Está excluido?')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número do Armário')),
                ('available', models.BooleanField(default=True, verbose_name='Disponivel')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='arduino.card', verbose_name='Cartão')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='clientes.client', verbose_name='Cliente')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='administrativo.enterprise', verbose_name='ID da empresa')),
            ],
            options={
                'verbose_name': 'Armário',
                'verbose_name_plural': 'Armários',
                'ordering': ['-created_at', 'available', 'number'],
            },
        ),
    ]
