# Generated by Django 5.1.6 on 2025-04-13 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_address_options_alter_address_address_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('business_name', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=14, verbose_name='Numero de telefone')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('address', models.ManyToManyField(related_name='entrepises', to='core.address', verbose_name='Endereços')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfid', models.CharField(max_length=8, verbose_name='RFID')),
                ('available', models.BooleanField(default=True, verbose_name='Disponivel')),
                ('enterpise_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='administrativo.enterprise', verbose_name='ID da empresa')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
                'ordering': ['-created_at', 'available'],
            },
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número do Armário')),
                ('available', models.BooleanField(default=True, verbose_name='Disponivel')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='administrativo.card', verbose_name='Cartão')),
                ('enterpise_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='administrativo.enterprise', verbose_name='ID da empresa')),
            ],
            options={
                'verbose_name': 'Armário',
                'verbose_name_plural': 'Armários',
                'ordering': ['-created_at', 'available'],
            },
        ),
    ]
