# Generated by Django 5.1.6 on 2025-05-01 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
        ('arduino', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='arduino.card', verbose_name='Cartão'),
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='enterpise_id',
            new_name='enterprise_id',
        ),
        migrations.AddField(
            model_name='locker',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='clientes.client', verbose_name='Cliente'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
