# Generated by Django 5.1.6 on 2025-04-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='enterpise_id',
            new_name='enterprise_id',
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='enterpise_id',
            new_name='enterprise_id',
        ),
    ]
