# Generated by Django 5.1.6 on 2025-05-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Está excluido?'),
        ),
        migrations.AddField(
            model_name='locker',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Está excluido?'),
        ),
    ]
