# Generated by Django 5.1.6 on 2025-04-24 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_rename_enterpise_id_card_enterprise_id_and_more'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='clientes.client', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
