# Generated by Django 5.1.6 on 2025-06-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_enterprise_is_deleted_locker_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locker',
            options={'ordering': ['-created_at', 'available', 'number'], 'verbose_name': 'Armário', 'verbose_name_plural': 'Armários'},
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='enterprise_id',
            new_name='enterprise',
        ),
    ]
