# Generated by Django 5.1.6 on 2025-04-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_locker_client_id'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='administrativo.card', verbose_name='Cartão'),
        ),
        migrations.AlterField(
            model_name='locker',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='clientes.client', verbose_name='Cliente'),
        ),
    ]
