# Generated by Django 5.1.6 on 2025-04-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at'], 'verbose_name': 'Endereco', 'verbose_name_plural': 'Enderecos'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='complemento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='reference_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ponto_referencia'),
        ),
    ]
