# Generated by Django 5.1.6 on 2025-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Está excluido?')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('phone', models.CharField(max_length=14, verbose_name='Número de telefone')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('access_level', models.IntegerField(choices=[(0, 'Super Usuário'), (1, 'Gerente'), (2, 'Cliente')], default=2, verbose_name='Nivel de acesso')),
                ('address', models.ManyToManyField(related_name='usuarios', to='core.address')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
